/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitMap;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException{
        System.out.println(new App().getGreeting());
        Bitmap summer = new Bitmap(args[0], args[1], args[2]);
    }

}
