/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitMap;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import java.awt.*;
import java.io.IOException;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test public void BlackAndWhiteTest() throws IOException{
        Bitmap classUnderTest = new Bitmap("summer", "summerBW", "BlackWhite");
        BufferedImage img = ImageIO.read(new File("./src/main/resources/summer.bmp"));
        BufferedImage result=classUnderTest.BlackAndWhite(img);
        assertNotNull(result);
    }

    @Test public void InvertImageTest() throws IOException{
        Bitmap classUnderTest = new Bitmap("summer", "summerInvert", "InvertImage");
        BufferedImage img = ImageIO.read(new File("./src/main/resources/summer.bmp"));
        BufferedImage result=classUnderTest.InvertImage(img);
        assertNotNull(result);
    }

    @Test public void DarkenImageTest() throws IOException{
        Bitmap classUnderTest = new Bitmap("summer", "summerDark", "DarkenImage");
        BufferedImage img = ImageIO.read(new File("./src/main/resources/summer.bmp"));
        BufferedImage result=classUnderTest.DarkenImage(img);
        assertNotNull(result);
    }
}
